"""Shared constants for graph RL observation."""

from __future__ import annotations

MAX_BASE_PLANETS = 40
MAX_COMETS = 4
MAX_NODES = MAX_BASE_PLANETS + MAX_COMETS
SHIP_BUCKETS = (1, 10, 50, 100)
NUM_SHIP_BUCKETS = len(SHIP_BUCKETS)
EDGE_FEAT_PER_BUCKET = 4
EDGE_FEAT_DIM = NUM_SHIP_BUCKETS * EDGE_FEAT_PER_BUCKET
GLOBAL_FEAT_DIM = 6
DEFAULT_HISTORY_STEPS = 5
DEFAULT_FUTURE_STEPS = 5
BASE_NODE_FEAT_DIM = 10
NUM_SEND_MODES = 4
